
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 29 17:06:29 PDT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 40;
  public static final int ST = 38;
  public static final int MASMAS = 13;
  public static final int CASFLOAT = 15;
  public static final int CASINT = 14;
  public static final int MENOSMENOS = 12;
  public static final int POR = 4;
  public static final int GE = 29;
  public static final int NOTEQUAL = 25;
  public static final int INT = 34;
  public static final int FOR = 18;
  public static final int CP = 9;
  public static final int NOT = 30;
  public static final int AND = 32;
  public static final int LT = 26;
  public static final int CL = 11;
  public static final int OR = 31;
  public static final int DIV = 5;
  public static final int IF = 16;
  public static final int LE = 27;
  public static final int EOF = 0;
  public static final int ASIG = 23;
  public static final int EQUAL = 24;
  public static final int error = 1;
  public static final int COMA = 22;
  public static final int MENOS = 3;
  public static final int MOD = 7;
  public static final int IDENT = 39;
  public static final int MENOSUNARIO = 6;
  public static final int REAL = 41;
  public static final int ELSE = 17;
  public static final int TO = 36;
  public static final int WHILE = 19;
  public static final int FLOAT = 35;
  public static final int DTO = 37;
  public static final int AP = 8;
  public static final int GT = 28;
  public static final int PRINT = 33;
  public static final int DO = 20;
  public static final int AL = 10;
  public static final int PYC = 21;
  public static final int MAS = 2;
}

